name: 🍿
title: 🍿
description: 🍿
baseurl: ""
paginate_path: "/_page/page:num/"
paginate: 9
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
url: https://iix21.github.io/
# Collections
collections:
  series:
    output: true
    permalink: /series/:title/
  franchises:
    output: false
    permalink: /franchise/:title/
  authors:
    output: false
  genre:
    output: true
    permalink: /genre/:title/
  countries:
    output: true
    permalink: /country/:title/
  languages:
    output: true
    permalink: /language/:title/
  subtitle:
    output: false
  director:
    output: false

# Defaults
defaults:
  # all Series
  - scope:
      path: ""
      type: "series"
    values:
      layout: "series"
  # all Languages
  - scope:
      path: ""
      type: "languages"
    values:
      layout: "language"
  # Franchises
  - scope:
      path: ""
      type: "franchises"
    values:
      layout: franchise
  # All genre
  - scope:
      path: ""
      type: "genre"
    values:
      layout: "genre"
  # All country
  - scope:
      path: ""
      type: "countries"
    values:
      layout: "country"
  # Indian Language
  - scope:
      path: "language"
    values:
      layout: language

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: /category/:name/

# Markdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
highlighter: rouge
include:
  - _pages
permalink: /:path/:title/

# Exclude
exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
